"""
Django settings for vocard project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import json
import sys
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = os.path.dirname(BASE_DIR)
SECRETS = os.path.join(BASE_DIR, 'secrets.json')
SERVICE_CRED = os.path.join(BASE_DIR, 'serviceAccountCredentials.json')
secrets = json.loads(open(SECRETS).read())
FIREBASE_CONFIG = {
    "apiKey": secrets['APIKEY'],
    "databaseURL": secrets["DATABASEURL"],
    "authDomain": secrets['AUTHDOMAIN'],
    "projectId": secrets['PROJECTID'],
    "storageBucket": secrets['STORAGEBUCKET'],
    "messagingSenderId": secrets['MESSAGINGSENDERID'],
    "appId": secrets['APPID'],
    "measurementId": secrets['MEASUREMENTID'],
    "serviceAccount": SERVICE_CRED
}
setattr(sys.modules[__name__], "FIREBASE_CONFIG", FIREBASE_CONFIG)
setattr(sys.modules[__name__], "OPENAI_API_KEY", secrets['OPENAI_API_KEY'])
setattr(sys.modules[__name__], "SOCIAL_AUTH_KAKAO_KEY", secrets['SOCIAL_AUTH_KAKAO_KEY'])
# had to set it to 4 to get a proper callback 
# todo: figure out why
# according to sites.objects.get(id=4)
# name = 127.0.0.1:8000, domain = name
SITE_ID = 0
# 5 = ec2 ip
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^$mh-6t1c6lwa1xid*vjgp$1v%%(j-o4=a%!$h5*z5%8ur6)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'authentication',
    'rest_framework',
    'vocard',
    'defaultword',
    'defaultwordexample',
    'defaultwordquiz',
    'defaultwordimg',
    'userexample',
    'user_stats',
    'openai_api',
    # OAuth
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    # filter backend
    'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'vocard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vocard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Authentication
AUTH_USER_MODEL = 'authentication.User'

REST_USE_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'oauth_id' 
ACCOUNT_EMAIL_REQUIRED = False            
ACCOUNT_USERNAME_REQUIRED = True        
ACCOUNT_AUTHENTICATION_METHOD = 'username'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],

}

# SOCIAL_AUTH_KAKAO_SCOPE = ['nickname']

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
